/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Episode = IDL.Record({
  'title' : IDL.Text,
  'description' : IDL.Text,
});
export const Webseries = IDL.Record({
  'title' : IDL.Text,
  'tagline' : IDL.Text,
  'episodes' : IDL.Vec(Episode),
});

export const idlService = IDL.Service({
  'getEpisodes' : IDL.Func([], [IDL.Vec(Episode)], ['query']),
  'getWebseries' : IDL.Func([], [Webseries], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Episode = IDL.Record({ 'title' : IDL.Text, 'description' : IDL.Text });
  const Webseries = IDL.Record({
    'title' : IDL.Text,
    'tagline' : IDL.Text,
    'episodes' : IDL.Vec(Episode),
  });
  
  return IDL.Service({
    'getEpisodes' : IDL.Func([], [IDL.Vec(Episode)], ['query']),
    'getWebseries' : IDL.Func([], [Webseries], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };